version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

    ignore:
      # For all images, ignore all major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
